image: docker:26.1.3

pipelines:
  default:
    - step:
        runs-on:
          - self.hosted
          - linux
        name: Build and Test
        services:
          - docker
        image: gradle:7.6.4-jdk17-focal
        caches:
          - gradle
          - docker
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - chmod +x gradlew
          - ./gradlew build
        after-script:
          - pipe: atlassian/checkstyle-report:0.3.0
        artifacts:
          - build/libs/sockbowl-questions-0.0.1-SNAPSHOT.jar
    - step:
        services:
          - docker
        caches:
          - docker
        runs-on:
          - self.hosted
          - linux
        name: Security Scan
        script:
          - pipe: atlassian/git-secrets-scan:0.5.1
    - step:
        services:
          - docker
        caches:
          - docker
        runs-on:
          - self.hosted
          - linux
        name: Publish to S3
        artifacts:
          download: true
        script:
          - chmod 777 build/libs/sockbowl-questions-0.0.1-SNAPSHOT.jar
          - mv build/libs/sockbowl-questions-0.0.1-SNAPSHOT.jar build/libs/sockbowl-questions-prod.jar
          - pipe: atlassian/aws-s3-deploy:1.6.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: 'sockbowl-us-east-1-prod-build-artifacts'
              LOCAL_PATH: 'build/libs/'
              S3_PATH: 'spring/bin/prod/'

definitions:
  services:
    docker:
      image: docker:26.1.3-dind
      privileged: true
